version: '3.1'

services:
  # mongodb
  mongo:
    image: mongo
    container_name: hooks_demo_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    volumes:
      - ./mongo/data:/data/db
  # server
  app:
    image: node:16.9.0-alpine
    container_name: hooks_demo
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
